### ISSUE TITLE
Zoom feature in detection area editor

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#18]
Editing would be easier in the detection area editor if there was zoom in/out feature.

**Comment by UFOID** [comment]
I am interested to know why you think this would be useful. I mostly just make a rough selection of the area I want to have included. Is there any scenario where one has to exactly select the detection area?

**Comment by hekkup** [comment]
There's at least one scenario in which zoom (or auto-scale) would be useful: screen resolution is big but web camera resolution is small. In that case web camera shows a small image in the middle of big window and it doesn't look too nice. I have this kind of situation to some extent.

**Comment by UFOID** [comment]
So if I understand it correctly the issue isn't being able to zoom in in order to carefully select the detection area with the precision of a few pixels but it is about the dialog not fitting the image from the webcam.
For this this I see two possible solutions. Fit the dialog around to the image size (easy) or fit the image to the dialog size (would need a update of the code that draws lines / reads the area from it).

**Comment by hekkup** [comment]
The web cam image is small (352x288) and it's not very nice to work with. Fitting dialog around the image is not good for that case, scaling image is better.
